name: Delete Deployment

on:
  delete:

jobs:
  delete:
    runs-on: ubuntu-latest
    name: Delete Deployment
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Enable corepack
        run: corepack enable

      - uses: oven-sh/setup-bun@v1

      - uses: actions/checkout@v4

      - name: Get Deleted Branch Name
        id: get_branch
        run: |
          branch_name=$(echo '${{ github.event.ref }}' | sed 's#refs/heads/##' | sed 's#[^a-zA-Z0-9]#-#g')
          echo "branch_name=$branch_name" >> $GITHUB_ENV
      - name: Retrieve and Construct Full Worker Name
        id: construct_worker_name
        run: |
          base_name=$(grep '^name = ' wrangler.toml | sed 's/^name = "\(.*\)"$/\1/')
          full_worker_name="${base_name}-${{ env.branch_name }}"
          # Make sure that it doesnt exceed 63 characters or it will break RFC 1035
          full_worker_name=$(echo "${full_worker_name}" | cut -c 1-63)
          echo "full_worker_name=$full_worker_name" >> $GITHUB_ENV
      - name: Delete Deployment with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: delete --name ${{ env.full_worker_name }}

      - name: Output Deletion Result
        run: |
          echo "### Deployment URL" >> $GITHUB_STEP_SUMMARY
          echo 'Deployment `${{ env.full_worker_name }}` has been deleted.' >> $GITHUB_STEP_SUMMARY
